services:
  - type: worker
    name: benefon-bot
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y libjpeg-dev zlib1g-dev
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8809330620:AAHGlFufsi1Eoz0HjXRvabumAzNo01Eg1R8
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_t7iEC1loVAIX@ep-delicate-fog-aoiuu6q0.c-2.ap-southeast-1.aws.neon.tech/neondb
      - key: LOCAL_DEBUG
        value: false
      - key: ADMIN_IDS
        value: 215432040
      - key: LOG_LEVEL
        value: INFO
